# Generated by Django 3.2.5 on 2022-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='candidate_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='detail_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='writer_id',
            field=models.TextField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
