# Generated by Django 3.2.5 on 2022-03-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate1App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
