# Generated by Django 3.2.5 on 2022-03-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebMember',
            fields=[
                ('member_id', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('member_pwd', models.TextField(max_length=100)),
                ('member_name', models.TextField(max_length=100)),
                ('member_poli', models.TextField(max_length=100)),
                ('member_age', models.DateField()),
                ('member_regdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
